package com.doctime.model.enums;

public enum Specialty {
    GENERAL_PRACTITIONER,
    CARDIOLOGIST,
    DERMATOLOGIST,
    NEUROLOGIST,
    ORTHOPEDIST,
    PEDIATRICIAN,
    PSYCHIATRIST,
    GYNECOLOGIST,
    OPHTHALMOLOGIST,
    ENT,
    DENTIST,
    ONCOLOGIST,
    RADIOLOGIST,
    OTHER
}
