package com.doctime.model.enums;

public enum Specialty {
    GENERAL_PHYSICIAN,
    CARDIOLOGIST,
    DERMATOLOGIST,
    PEDIATRICIAN,
    GYNECOLOGIST,
    ORTHOPEDIC,
    ENT_SPECIALIST,
    PSYCHIATRIST,
    NEUROLOGIST,
    OPHTHALMOLOGIST,
    DENTIST,
    UROLOGIST,
    GASTROENTEROLOGIST,
    ENDOCRINOLOGIST,
    PULMONOLOGIST
}
